version: 2
jobs:
  build/docker:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - restore_cache:
          - name:
            - konker_jars 
      - run:
          name: prepare for build container for api
          command: cp ~/.m2/repository/com/konkerlabs/konker.registry.api/1.5.1.RELEASE/konker.registry.api-1.5.1.RELEASE.jar konker.registry.api/docker-resources/registry-api.jar
      - run:
          name: build container for api
          command: docker build .
  build/java:
    docker: 
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name:  Install utitilties
          command: mvn clean install -pl  konker.utilities/pom.xml -DskipTests
      - run:
          name:  Install security
          command: mvn clean install -pl  konker.security/pom.xml -DskipTests
      - run:
          name:  Install services
          command: mvn clean install -DskipTests
      - store_artifacts:
          path: ~/.m2/repository/com/konkerlabs
          name: konker_jars
      #- run:
      #    name:  Install data core
      #    command: mvn clean install -pl  konker.registry.data.core/pom.xml -DskipTests
      #- run:
      #    name:  Install storage cassandra
      #    command: mvn clean install -pl  konker.registry.services.storage.cassandra/pom.xml -DskipTests
      #- run:
      #    name:  Install storage mongodb
      #   command: mvn clean install -pl  konker.registry.services.storage.mongodb/pom.xml -DskipTests
      #- run:
      #    name:  Install api 
      #    command: mvn clean install -pl  konker.registry.api/pom.xml -DskipTests
      #- run:
      #    name:  Install data 
      #    command: mvn clean install -pl  konker.registry.data/pom.xml -DskipTests
      #- run:
      #    name:  Install data processor 
      #   command: mvn clean install -pl  konker.registry.data.processor/pom.xml -DskipTests
      #- run:
      #    name:  Install web 
      #    command: mvn clean install -pl  konker.registry.web/pom.xml -DskipTests
      #- run:
      #    name:  Install IDM 
      #    command: mvn clean install -pl  konker.registry.idm.resourceserver/pom.xml -DskipTests

workflows:
  maven:
    jobs:
      - build/java
      - build/docker:
          requires: 
            - build/java
  version: 2
      


        
        
