version: 2
jobs:
  maven/test:
    docker: 
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name:  Install deps
          command: mvn clean install -pl  konker.utilities/pom.xml -DskipTests
workflows:
  maven_test:
    jobs:
      - maven/test
  version: 2
      


        
        
